### ISSUE TITLE
Suggest paragraph removal for confusion and non-relevance

### ISSUE THREAD

**Issue by raiet13** [learn-co-curriculum/using-active-model-serializer#10]
Noted paragraph: "And now if we reload our first post show page and click through our Next button we can see that everything works exactly the same as before!"

Issue : This paragraph is particularly confusing for this readme given that the readme directory doesn't actually have a "views" folder. It is also the only mention of the html version of a show page.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #20. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
