### ISSUE TITLE
Error unrelated to lab and also not correct

### ISSUE THREAD

**Issue by malbazaz** [learn-co-curriculum/using-active-model-serializer#11]
This lab is not testing views, but I added views because the failures/spec were asking for. When you render this through rails s, it shows the form correctly and the form works. However, the following error prints: 
1) form shows a new form that submits content and redirects and prints out params
     Failure/Error: fill_in 'title', with: "My post title"
     Capybara::ElementNotFound:
       Unable to find field "title"

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #20. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
