### ISSUE TITLE
Something is seriously wrong with this section's lesson submissions

### ISSUE THREAD

**Issue by AkaKuro4Ever** [learn-co-curriculum/using-active-model-serializer#12]
Just like the `Returning String Data, `DIY JSON Serializer Codealong` and `Using to_json`, and most likely `Receiving API Posts`, I sent an error that none of these turned green for me. Now, the labs have been updated to need the specs to pass. 

The specs for these labs are all GENERIC, and exactly the same one. And they need intense revision to basic Rails code in order to make them pass each time. It's time consuming and long. Also, because I already finished these, I am having to go back and try to get Learn to recognize that I had already forked them (because they forgot I forked them), and basically force all these diverse labs to pass the same EXACT spec every time. These should have just been pull request-only, not spec-driven, since these are lessons. Not labs.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #20. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #20. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
