### ISSUE TITLE
Specs don't match for this code-along

### ISSUE THREAD

**Issue by SilverBright** [learn-co-curriculum/using-active-model-serializer#16]
Commented out all specs in order to 'pass' and move on to next lab.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #20. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
