### ISSUE TITLE
Specs don't go with this code-along

### ISSUE THREAD

**Issue by dapawn** [learn-co-curriculum/using-active-model-serializer#17]
The lesson is about coding API's not about views, but the specs are checking the views, and forms, which was not part of the code-along.

I commented out the `  it 'shows the title on the show page in a h1 tag' do` section and the whole `describe 'form' do` section to pass the lesson.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #20. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
