### ISSUE TITLE
Test spec and rails last version in the Gemfile are to be fixed.

### ISSUE THREAD

**Issue by Emanao** [learn-co-curriculum/using-active-model-serializer#18]
I had 2 issues while coding along this lesson:
1. I couldnt bundle install with the version in the Gemfile that I got from forking the lesson.
Rails v.5 is needed for this lesson.
2. Test spec problem already mentioned in other issues:
rendering only happened on the json side. There is no html rendering in the controller and no views for that. Test spec expect them though... 
To pass the tests and have the lesson working:
Change rails gem in the Gemfile to 5 and comment the specs related to view expectations.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #20. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
