### ISSUE TITLE
Specs non-existant but lesson want them run

### ISSUE THREAD

**Issue by LLHolmes** [learn-co-curriculum/using-active-model-serializer#19]
The lesson expects local tests to be run before submitting, but there are not test specs in this lab.

**Comment by gac2117** [comment]
Tech coach told me to run `rails generate rspec:install` and then `learn` to pass

**Comment by catherinism** [comment]
thank you @gac2117

**Comment by FreeBreadsticks** [comment]
@drakeltheryuujin looks like this lab expects tests to run but there are no tests built into the lab itself.

**Comment by jhharwood88** [comment]
Trying this solution i hit gem dependency errors. Not totally sure if this is my own local having issues or the gem file itself. 

Ubuntu 18.10

[15:41:19] (master) using-active-model-serializer-online-web-ft-031119
// ♥ rails generate rspec:install
Traceback (most recent call last):
	17: from bin/rails:4:in `<main>'
	16: from bin/rails:4:in `require'
	15: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
	14: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	13: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:60:in `generate'
	12: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:143:in `generate_or_destroy'
	11: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:156:in `require_application_and_environment!'
	10: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:156:in `require'
	 9: from /home/jon-laptop/code/labs/using-active-model-serializer-online-web-ft-031119/config/application.rb:7:in `<top (required)>'
	 8: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler.rb:114:in `require'
	 7: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `require'
	 6: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `each'
	 5: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `block in require'
	 4: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `each'
	 3: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	 2: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `require'
	 1: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/sqlite3-1.3.13/lib/sqlite3.rb:4:in `<top (required)>'
/home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/sqlite3-1.3.13/lib/sqlite3.rb:4:in `require': cannot load such file -- sqlite3/2.6/sqlite3_native (LoadError)
	18: from bin/rails:4:in `<main>'
	17: from bin/rails:4:in `require'
	16: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
	15: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	14: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:60:in `generate'
	13: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:143:in `generate_or_destroy'
	12: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:156:in `require_application_and_environment!'
	11: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:156:in `require'
	10: from /home/jon-laptop/code/labs/using-active-model-serializer-online-web-ft-031119/config/application.rb:7:in `<top (required)>'
	 9: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler.rb:114:in `require'
	 8: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `require'
	 7: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:65:in `each'
	 6: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `block in require'
	 5: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:76:in `each'
	 4: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	 3: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/bundler-2.0.1/lib/bundler/runtime.rb:81:in `require'
	 2: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/sqlite3-1.3.13/lib/sqlite3.rb:2:in `<top (required)>'
	 1: from /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/sqlite3-1.3.13/lib/sqlite3.rb:6:in `rescue in <top (required)>'
/home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/sqlite3-1.3.13/lib/sqlite3.rb:6:in `require': incompatible library version - /home/jon-laptop/.rvm/gems/ruby-2.6.3/gems/sqlite3-1.3.13/lib/sqlite3/sqlite3_native.so (LoadError)

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #20. 

We will add this to our internal work queue. We are in the process of updating
the materials in this section and will be rewriting this lesson to address the
current issues. We'll be taking all of this information into consideration in
upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when it is resolved.

Thanks for contributing!
